''' This file is automatically generated. '''

class Produto:

    _attribute_types = {
        "prod_id":"INT", "prod_name":"TEXT", "prod_spec":"TEXT"
    }

    _primary_key = ["prod_id"]

    def __init__(self, **kargs):
        self.prod_id = kargs["prod_id"]
        self.prod_name = kargs["prod_name"]
        self.prod_spec = kargs["prod_spec"]

class Loja:

    _attribute_types = {
        "l_nick":"TEXT", "l_name":"TEXT", "l_credit":"BOOL", "l_delivery":"BOOL", "l_address":"TEXT"
    }

    _primary_key = ["l_nick"]

    def __init__(self, **kargs):
        self.l_nick = kargs["l_nick"]
        self.l_name = kargs["l_name"]
        self.l_credit = kargs["l_credit"]
        self.l_delivery = kargs["l_delivery"]
        self.l_address = kargs["l_address"]

class Anuncio:

    _attribute_types = {
        "l_nick":"TEXT", "prod_id":"INT", "prod_price":"FLOAT", "time_catch":"TEXT"
    }

    _primary_key = ["l_nick", "prod_id", "prod_price"]

    _foreign_key = {
        "l_nick":"Loja", "prod_id":"Produto"
    }

    def __init__(self, **kargs):
        self.l_nick = kargs["l_nick"]
        self.prod_id = kargs["prod_id"]
        self.prod_price = kargs["prod_price"]
        self.time_catch = kargs["time_catch"]

class Meta:

    _attribute_types = {
        "metakey":"INT", "range_start":"INT", "range_end":"INT"
    }

    _primary_key = ["metakey"]

    def __init__(self, **kargs):
        self.metakey = kargs["metakey"]
        self.range_start = kargs["range_start"]
        self.range_end = kargs["range_end"]

